In [12]:
import magic

import numpy as np
import scanpy as sc
import pandas as pd
import os

In [23]:
### 随机取得583个细胞
###583个细胞

import magic
import numpy as np
import scanpy as sc
import pandas as pd
import os

In [ ]:
dge = pd.read_csv('./PBMC/pbmc583cell_counts.tsv',sep='\t',index_col=0)
dge.shape

(27051, 4645)

In [13]:
dge.iloc[:3,:6]

,PBMC1.Smart-seq2.p2_A1,PBMC1.Smart-seq2.p2_B4,PBMC1.Smart-seq2.p4_A12,PBMC1.Smart-seq2.p4_A2,PBMC1.Smart-seq2.p4_A3,PBMC1.Smart-seq2.p4_A4
TSPAN6,0,0,0,0,0,0
TNMD,0,0,0,0,0,0
DPM1,0,0,0,0,0,0

In [25]:
adata = sc.AnnData(dge.T)
adata.var_names_make_unique()
adata

AnnData object with n_obs × n_vars = 4645 × 27051

In [26]:
sc.pp.normalize_total(adata, target_sum = 1e6)
sc.pp.filter_genes(adata, min_cells = 1)
# sc.pp.filter_cells(adata, min_genes = 50)

sc.pp.log1p(adata, base = 2)
print(adata)

AnnData object with n_obs × n_vars = 4645 × 26374
    var: 'n_cells'
    uns: 'log1p'

In [27]:
df = adata.to_df().T
#df.to_pickle('/home/ggj/Galaxy/01_benmark_data/01_run/02_BIB_PBMC_tech/adata_pbmc_583cells.p')

In [29]:
#df = pd.read_pickle("/home/ggj/Galaxy/01_benmark_data/01_run/02_BIB_PBMC_tech/adata_pbmc_583cells.p")
print(df.shape)
print(df.values.max())
print(np.median(df.values)) 
print(df.values.min())
#df.iloc[:3,:5]

(26374, 4645)
19.118515
0.0
0.0

In [ ]:
df.to_pickle("./d4_PCC_baseline_PBMC_583cells/adata_pbmc_583cells_PCC.p")

In [ ]:
df = pd.read_pickle("./d4_PCC_baseline_PBMC_583cells/adata_pbmc_583cells_PCC.p")
print(df.shape)
df[:2]

(26374, 4645)

,PBMC1.Smart-seq2.p2_A1,PBMC1.Smart-seq2.p2_B4,PBMC1.Smart-seq2.p4_A12,PBMC1.Smart-seq2.p4_A2,PBMC1.Smart-seq2.p4_A3,PBMC1.Smart-seq2.p4_A4,PBMC1.Smart-seq2.p4_A7,PBMC1.Smart-seq2.p4_A8,PBMC1.Smart-seq2.p4_A9,PBMC1.Smart-seq2.p4_B1,...,PBMC2.inDrops.TGAATAGG-TTATGCGA-CACTTTCT,PBMC2.inDrops.TGAATCCT-TTATGCGA-AAACCTCC,PBMC2.inDrops.TGAGAGCG-TTATGCGA-CAGACCAT,PBMC2.inDrops.TGAGAGCG-TTATGCGA-TCTAGCAG,PBMC2.inDrops.TGAGAGCG-TTATGCGA-TCTGTGGT,PBMC2.inDrops.TGAGCACA-GAGCCTTA-TTCCGAGT,PBMC2.inDrops.TGCGACTA-TTATGCGA-TGTTCCAG,PBMC2.inDrops.TGCTTCAT-TTATGCGA-GTTTACGT,PBMC2.inDrops.TGGACGGA-GAGCCTTA-TGGCTACC,PBMC2.inDrops.TGGGAATT-TTATGCGA-AGGTTGTG
TSPAN6,0.0,0.0,0.0,0.0,0.0,0.0,1.940551,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TNMD,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
print(df.values.max())
print(np.median(df.values)) 
print(df.values.min())

19.118515
0.0
0.0

In [8]:
df_cutoff_001 = df.copy()
df_cutoff_001[:] = np.where(df_cutoff_001>=0.001, 1, 0)
df_cutoff_001.stack().value_counts()

0.0    116053535
1.0      6453695
Name: count, dtype: int64

In [ ]:
df_cutoff_001.to_pickle("./d3_baseline_cutoff001_583cells/adata_pbmc_583cells_cutoff001.p")

In [ ]:
annotation = pd.read_csv("./00_processed_data/PBMC/Human_sctechnologies.annotation.tsv",sep = '\t')
print(annotation.shape)
print(annotation['Cluster'].unique())
annotation[:3]

(41682, 4)
['Smart-seq2' 'CEL-Seq2' '10x-Chromium-V2' '10x-Chromium-v3' 'Drop-seq'
 'Seq-Well' 'inDrops' '10x-Chromium-v2']

                      Cell Species             Celltype     Cluster
0   PBMC1.Smart-seq2.p2_A1   Human  PBMC1.Smart-seq2.p2  Smart-seq2
1   PBMC1.Smart-seq2.p2_B4   Human  PBMC1.Smart-seq2.p2  Smart-seq2
2  PBMC1.Smart-seq2.p4_A12   Human  PBMC1.Smart-seq2.p4  Smart-seq2

In [18]:
annotation2 = annotation[annotation['Cell'].isin(df.columns)]
print(annotation2.shape)
print(annotation2['Cluster'].value_counts())
annotation2[:3]

(4645, 4)
Cluster
Smart-seq2         583
10x-Chromium-V2    583
10x-Chromium-v3    583
Drop-seq           583
inDrops            583
Seq-Well           583
10x-Chromium-v2    583
CEL-Seq2           564
Name: count, dtype: int64

                      Cell Species             Celltype     Cluster
0   PBMC1.Smart-seq2.p2_A1   Human  PBMC1.Smart-seq2.p2  Smart-seq2
1   PBMC1.Smart-seq2.p2_B4   Human  PBMC1.Smart-seq2.p2  Smart-seq2
2  PBMC1.Smart-seq2.p4_A12   Human  PBMC1.Smart-seq2.p4  Smart-seq2

In [ ]:
annotation2.to_csv("./d3_baseline_cutoff001_583cells/Human_sctechnologies_annotation_583cells.tsv", sep='\t', index=None)

In [3]:
############## 统计检测基因数目
import numpy as np
import scanpy as sc
import pandas as pd

In [ ]:
###### 583cells
df = pd.read_pickle("./d4_PCC_baseline_PBMC_583cells/adata_pbmc_583cells_PCC.p")

In [15]:
df[:2]

,PBMC1.Smart-seq2.p2_A1,PBMC1.Smart-seq2.p2_B4,PBMC1.Smart-seq2.p4_A12,PBMC1.Smart-seq2.p4_A2,PBMC1.Smart-seq2.p4_A3,PBMC1.Smart-seq2.p4_A4,PBMC1.Smart-seq2.p4_A7,PBMC1.Smart-seq2.p4_A8,PBMC1.Smart-seq2.p4_A9,PBMC1.Smart-seq2.p4_B1,...,PBMC2.inDrops.TGAATAGG-TTATGCGA-CACTTTCT,PBMC2.inDrops.TGAATCCT-TTATGCGA-AAACCTCC,PBMC2.inDrops.TGAGAGCG-TTATGCGA-CAGACCAT,PBMC2.inDrops.TGAGAGCG-TTATGCGA-TCTAGCAG,PBMC2.inDrops.TGAGAGCG-TTATGCGA-TCTGTGGT,PBMC2.inDrops.TGAGCACA-GAGCCTTA-TTCCGAGT,PBMC2.inDrops.TGCGACTA-TTATGCGA-TGTTCCAG,PBMC2.inDrops.TGCTTCAT-TTATGCGA-GTTTACGT,PBMC2.inDrops.TGGACGGA-GAGCCTTA-TGGCTACC,PBMC2.inDrops.TGGGAATT-TTATGCGA-AGGTTGTG
TSPAN6,0.0,0.0,0.0,0.0,0.0,0.0,1.940551,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TNMD,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
annotation2 =  pd.read_csv('./d3_baseline_cutoff001_583cells/Human_sctechnologies_annotation_583cells.tsv',sep='\t')

In [4]:
gene_detected_PCC = np.where(df > 0, 1, 0).sum(0) 
print(gene_detected_PCC.shape)
gene_detected_AUROC = np.where(df >= 0.001, 1, 0).sum(0) 
print(gene_detected_AUROC.shape)

(4645,)
(4645,)

In [9]:
annotation2["gene_detected_PCC"] = gene_detected_PCC
annotation2["gene_detected_AUROC"] = gene_detected_AUROC
annotation2.head()

,Cell,Species,Celltype,Cluster,gene_detected_PCC,gene_detected_AUROC
0,PBMC1.Smart-seq2.p2_A1,Human,PBMC1.Smart-seq2.p2,Smart-seq2,1623,1623
1,PBMC1.Smart-seq2.p2_B4,Human,PBMC1.Smart-seq2.p2,Smart-seq2,2415,2415
2,PBMC1.Smart-seq2.p4_A12,Human,PBMC1.Smart-seq2.p4,Smart-seq2,2909,2909
3,PBMC1.Smart-seq2.p4_A2,Human,PBMC1.Smart-seq2.p4,Smart-seq2,2062,2062
4,PBMC1.Smart-seq2.p4_A3,Human,PBMC1.Smart-seq2.p4,Smart-seq2,2100,2100

In [22]:
Detected_gene = annotation2.groupby('Cluster')[['gene_detected_PCC','gene_detected_AUROC']].mean().round().reset_index()
Detected_gene

           Cluster  gene_detected_PCC  gene_detected_AUROC
0  10x-Chromium-V2             1004.0               1004.0
1  10x-Chromium-v2             1166.0               1166.0
2  10x-Chromium-v3             1772.0               1772.0
3         CEL-Seq2             2604.0               2604.0
4         Drop-seq              866.0                866.0
5         Seq-Well              591.0                591.0
6       Smart-seq2             2606.0               2606.0
7          inDrops              546.0                546.0

In [ ]:
### MAGIC
df_magic =  pd.read_pickle("./d5_MAGIC_cutoff03_583cells/adata_PBMC_MAGIC_583cells.p")
print(df_magic.shape)

(26374, 4643)

In [17]:
df_magic[:2]

,MAGIC-PBMC1.Smart-seq2.p4_A12,MAGIC-PBMC1.Smart-seq2.p4_A2,MAGIC-PBMC1.Smart-seq2.p4_A3,MAGIC-PBMC1.Smart-seq2.p4_A4,MAGIC-PBMC1.Smart-seq2.p4_A7,MAGIC-PBMC1.Smart-seq2.p4_A8,MAGIC-PBMC1.Smart-seq2.p4_A9,MAGIC-PBMC1.Smart-seq2.p4_B1,MAGIC-PBMC1.Smart-seq2.p2_B5,MAGIC-PBMC1.Smart-seq2.p4_B10,...,MAGIC-PBMC2.inDrops.TGAATAGG-TTATGCGA-CACTTTCT,MAGIC-PBMC2.inDrops.TGAATCCT-TTATGCGA-AAACCTCC,MAGIC-PBMC2.inDrops.TGAGAGCG-TTATGCGA-CAGACCAT,MAGIC-PBMC2.inDrops.TGAGAGCG-TTATGCGA-TCTAGCAG,MAGIC-PBMC2.inDrops.TGAGAGCG-TTATGCGA-TCTGTGGT,MAGIC-PBMC2.inDrops.TGAGCACA-GAGCCTTA-TTCCGAGT,MAGIC-PBMC2.inDrops.TGCGACTA-TTATGCGA-TGTTCCAG,MAGIC-PBMC2.inDrops.TGCTTCAT-TTATGCGA-GTTTACGT,MAGIC-PBMC2.inDrops.TGGACGGA-GAGCCTTA-TGGCTACC,MAGIC-PBMC2.inDrops.TGGGAATT-TTATGCGA-AGGTTGTG
TSPAN6,0.109723,0.181646,0.075158,0.116502,0.161529,0.110286,0.105154,0.082984,0.131318,0.120644,...,0.013889,0.003145,0.004863,0.009698,0.001725,0.015106,0.005213,0.016173,0.005972,0.002791
TNMD,0.000000,0.015524,0.000039,0.000000,0.018532,0.041362,0.016647,0.001406,0.016901,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [5]:
print(df_magic.values.max())
print(np.median(df_magic.values)) 
print(df_magic.values.min())

16.084100261812683
0.027479642146248574
0.0

In [ ]:
annotation_magic =  pd.read_csv('./d5_MAGIC_cutoff03_583cells/annotation583cell_MAGIC.tsv',sep='\t')
print(annotation_magic.shape)
annotation_magic[:2]

(4643, 4)

,Cell,Species,Celltype,Cluster
0,MAGIC-PBMC1.Smart-seq2.p4_A12,MAGIC-Human,MAGIC-PBMC1.Smart-seq2.p4,MAGIC-Smart-seq2
1,MAGIC-PBMC1.Smart-seq2.p4_A2,MAGIC-Human,MAGIC-PBMC1.Smart-seq2.p4,MAGIC-Smart-seq2

In [6]:
gene_detected_magic_PCC = np.where(df_magic > 0, 1, 0).sum(0) 
print(gene_detected_magic_PCC.shape)
gene_detected_magic_AUROC = np.where(df_magic >= 0.027, 1, 0).sum(0) 
print(gene_detected_magic_AUROC.shape)

(4643,)
(4643,)

In [ ]:
df_magic_cutoff_t.stack().value_counts()

In [8]:
annotation_magic["gene_detected_PCC"] = gene_detected_magic_PCC
annotation_magic["gene_detected_AUROC"] = gene_detected_magic_AUROC

In [9]:
annotation_magic[:2]

,Cell,Species,Celltype,Cluster,gene_detected_PCC,gene_detected_AUROC
0,MAGIC-PBMC1.Smart-seq2.p4_A12,MAGIC-Human,MAGIC-PBMC1.Smart-seq2.p4,MAGIC-Smart-seq2,21615,16863
1,MAGIC-PBMC1.Smart-seq2.p4_A2,MAGIC-Human,MAGIC-PBMC1.Smart-seq2.p4,MAGIC-Smart-seq2,23942,17688

In [ ]:
annotation_magic.to_csv("./d3_DetectedGene/annotation_PBMC_magic.tsv",index=None)
annotation2.to_csv("./d3_DetectedGene/annotation_PBMC.tsv",index=None)

In [1]:
import magic

import numpy as np
import scanpy as sc
import pandas as pd
import os

In [ ]:
###### 583cells
df = pd.read_pickle("./d4_PCC_baseline_PBMC_583cells/adata_pbmc_583cells_PCC.p")

In [ ]:
annotation = pd.read_csv("./d3_baseline_cutoff001_583cells/Human_sctechnologies_annotation_583cells.tsv", sep='\t')
print(annotation.shape)
annotation[:2]

(4645, 4)

                     Cell Species             Celltype     Cluster
0  PBMC1.Smart-seq2.p2_A1   Human  PBMC1.Smart-seq2.p2  Smart-seq2
1  PBMC1.Smart-seq2.p2_B4   Human  PBMC1.Smart-seq2.p2  Smart-seq2

In [36]:
df_magic = []
for Tech in np.unique(annotation.Cluster.values):
    df_adata = df.iloc[:, annotation.Cluster.values==Tech].T
    
    if Tech == "BulkSeq":
        pass #df_magic.append(df_adata)
    else:
        magic_op = magic.MAGIC()
        df_adata_magic = magic_op.fit_transform(df_adata)

        print(df_adata_magic.shape)
        df_magic.append(df_adata_magic)
        
df_magic = pd.concat(df_magic, axis=0).T
df_magic = df_magic[annotation.iloc[2:,].Cell] # sort df_magic cell_i

Calculating MAGIC...
  Running MAGIC on 583 cells and 26374 genes.
  Calculating graph and diffusion operator...
    Calculating PCA...

/home/ggj/.local/lib/python3.11/site-packages/magic_impute-3.0.0-py3.11.egg/magic/magic.py:425: UserWarning: Input matrix contains unexpressed genes. Please remove them prior to running MAGIC.
  warnings.warn(

    Calculated PCA in 0.43 seconds.
    Calculating KNN search...
    Calculated KNN search in 0.07 seconds.
    Calculating affinities...
    Calculated affinities in 0.07 seconds.
  Calculated graph and diffusion operator in 0.59 seconds.
  Running MAGIC with `solver='exact'` on 26374-dimensional data may take a long time. Consider denoising specific genes with `genes=<list-like>` or using `solver='approximate'`.
  Calculating imputation...
  Calculated imputation in 0.10 seconds.
Calculated MAGIC in 0.74 seconds.
(583, 26374)
Calculating MAGIC...
  Running MAGIC on 583 cells and 26374 genes.
  Calculating graph and diffusion operator...
    Calculating PCA...

/home/ggj/.local/lib/python3.11/site-packages/magic_impute-3.0.0-py3.11.egg/magic/magic.py:425: UserWarning: Input matrix contains unexpressed genes. Please remove them prior to running MAGIC.
  warnings.warn(

    Calculated PCA in 0.40 seconds.
    Calculating KNN search...
    Calculated KNN search in 0.07 seconds.
    Calculating affinities...
    Calculated affinities in 0.07 seconds.
  Calculated graph and diffusion operator in 0.57 seconds.
  Running MAGIC with `solver='exact'` on 26374-dimensional data may take a long time. Consider denoising specific genes with `genes=<list-like>` or using `solver='approximate'`.
  Calculating imputation...
  Calculated imputation in 0.12 seconds.
Calculated MAGIC in 0.73 seconds.
(583, 26374)
Calculating MAGIC...
  Running MAGIC on 583 cells and 26374 genes.
  Calculating graph and diffusion operator...
    Calculating PCA...

/home/ggj/.local/lib/python3.11/site-packages/magic_impute-3.0.0-py3.11.egg/magic/magic.py:425: UserWarning: Input matrix contains unexpressed genes. Please remove them prior to running MAGIC.
  warnings.warn(

    Calculated PCA in 0.40 seconds.
    Calculating KNN search...
    Calculated KNN search in 0.07 seconds.
    Calculating affinities...
    Calculated affinities in 0.07 seconds.
  Calculated graph and diffusion operator in 0.56 seconds.
  Running MAGIC with `solver='exact'` on 26374-dimensional data may take a long time. Consider denoising specific genes with `genes=<list-like>` or using `solver='approximate'`.
  Calculating imputation...
  Calculated imputation in 0.12 seconds.
Calculated MAGIC in 0.71 seconds.
(583, 26374)
Calculating MAGIC...
  Running MAGIC on 564 cells and 26374 genes.
  Calculating graph and diffusion operator...
    Calculating PCA...

/home/ggj/.local/lib/python3.11/site-packages/magic_impute-3.0.0-py3.11.egg/magic/magic.py:425: UserWarning: Input matrix contains unexpressed genes. Please remove them prior to running MAGIC.
  warnings.warn(

    Calculated PCA in 0.40 seconds.
    Calculating KNN search...
    Calculated KNN search in 0.06 seconds.
    Calculating affinities...
    Calculated affinities in 0.06 seconds.
  Calculated graph and diffusion operator in 0.54 seconds.
  Running MAGIC with `solver='exact'` on 26374-dimensional data may take a long time. Consider denoising specific genes with `genes=<list-like>` or using `solver='approximate'`.
  Calculating imputation...
  Calculated imputation in 0.12 seconds.
Calculated MAGIC in 0.70 seconds.
(564, 26374)
Calculating MAGIC...
  Running MAGIC on 583 cells and 26374 genes.
  Calculating graph and diffusion operator...
    Calculating PCA...

/home/ggj/.local/lib/python3.11/site-packages/magic_impute-3.0.0-py3.11.egg/magic/magic.py:425: UserWarning: Input matrix contains unexpressed genes. Please remove them prior to running MAGIC.
  warnings.warn(

    Calculated PCA in 0.40 seconds.
    Calculating KNN search...
    Calculated KNN search in 0.07 seconds.
    Calculating affinities...
    Calculated affinities in 0.07 seconds.
  Calculated graph and diffusion operator in 0.55 seconds.
  Running MAGIC with `solver='exact'` on 26374-dimensional data may take a long time. Consider denoising specific genes with `genes=<list-like>` or using `solver='approximate'`.
  Calculating imputation...
  Calculated imputation in 0.12 seconds.
Calculated MAGIC in 0.72 seconds.
(583, 26374)
Calculating MAGIC...
  Running MAGIC on 583 cells and 26374 genes.
  Calculating graph and diffusion operator...
    Calculating PCA...

/home/ggj/.local/lib/python3.11/site-packages/magic_impute-3.0.0-py3.11.egg/magic/magic.py:425: UserWarning: Input matrix contains unexpressed genes. Please remove them prior to running MAGIC.
  warnings.warn(

    Calculated PCA in 0.40 seconds.
    Calculating KNN search...
    Calculated KNN search in 0.07 seconds.
    Calculating affinities...
    Calculated affinities in 0.07 seconds.
  Calculated graph and diffusion operator in 0.56 seconds.
  Running MAGIC with `solver='exact'` on 26374-dimensional data may take a long time. Consider denoising specific genes with `genes=<list-like>` or using `solver='approximate'`.
  Calculating imputation...
  Calculated imputation in 0.12 seconds.
Calculated MAGIC in 0.72 seconds.
(583, 26374)
Calculating MAGIC...
  Running MAGIC on 583 cells and 26374 genes.
  Calculating graph and diffusion operator...
    Calculating PCA...

/home/ggj/.local/lib/python3.11/site-packages/magic_impute-3.0.0-py3.11.egg/magic/magic.py:425: UserWarning: Input matrix contains unexpressed genes. Please remove them prior to running MAGIC.
  warnings.warn(

    Calculated PCA in 0.42 seconds.
    Calculating KNN search...
    Calculated KNN search in 0.07 seconds.
    Calculating affinities...
    Calculated affinities in 0.07 seconds.
  Calculated graph and diffusion operator in 0.57 seconds.
  Running MAGIC with `solver='exact'` on 26374-dimensional data may take a long time. Consider denoising specific genes with `genes=<list-like>` or using `solver='approximate'`.
  Calculating imputation...
  Calculated imputation in 0.12 seconds.
Calculated MAGIC in 0.73 seconds.
(583, 26374)
Calculating MAGIC...
  Running MAGIC on 583 cells and 26374 genes.
  Calculating graph and diffusion operator...
    Calculating PCA...

/home/ggj/.local/lib/python3.11/site-packages/magic_impute-3.0.0-py3.11.egg/magic/magic.py:425: UserWarning: Input matrix contains unexpressed genes. Please remove them prior to running MAGIC.
  warnings.warn(

    Calculated PCA in 0.41 seconds.
    Calculating KNN search...
    Calculated KNN search in 0.07 seconds.
    Calculating affinities...
    Calculated affinities in 0.07 seconds.
  Calculated graph and diffusion operator in 0.57 seconds.
  Running MAGIC with `solver='exact'` on 26374-dimensional data may take a long time. Consider denoising specific genes with `genes=<list-like>` or using `solver='approximate'`.
  Calculating imputation...
  Calculated imputation in 0.12 seconds.
Calculated MAGIC in 0.73 seconds.
(583, 26374)

In [47]:
df_magic.shape

(26374, 4643)

In [49]:
annotation2 = annotation[annotation['Cell'].isin(df_magic.columns)]
print(annotation2.shape)
print(annotation2['Cluster'].value_counts())
annotation2[:3]

(4643, 4)
Cluster
10x-Chromium-v3    583
10x-Chromium-V2    583
Seq-Well           583
Drop-seq           583
inDrops            583
10x-Chromium-v2    583
Smart-seq2         581
CEL-Seq2           564
Name: count, dtype: int64

                      Cell Species             Celltype     Cluster
2  PBMC1.Smart-seq2.p4_A12   Human  PBMC1.Smart-seq2.p4  Smart-seq2
3   PBMC1.Smart-seq2.p4_A2   Human  PBMC1.Smart-seq2.p4  Smart-seq2
4   PBMC1.Smart-seq2.p4_A3   Human  PBMC1.Smart-seq2.p4  Smart-seq2

In [50]:
annotation_magic = annotation2.copy()
annotation_magic.Cell = annotation2.Cell.apply(lambda x:"MAGIC-"+x)
annotation_magic.Species = annotation2.Species.apply(lambda x:"MAGIC-"+x)
annotation_magic.Celltype = annotation2.Celltype.apply(lambda x:"MAGIC-"+x)
annotation_magic.Cluster = annotation2.Cluster.apply(lambda x:"MAGIC-"+x)
annotation_magic[:3]

,Cell,Species,Celltype,Cluster
2,MAGIC-PBMC1.Smart-seq2.p4_A12,MAGIC-Human,MAGIC-PBMC1.Smart-seq2.p4,MAGIC-Smart-seq2
3,MAGIC-PBMC1.Smart-seq2.p4_A2,MAGIC-Human,MAGIC-PBMC1.Smart-seq2.p4,MAGIC-Smart-seq2
4,MAGIC-PBMC1.Smart-seq2.p4_A3,MAGIC-Human,MAGIC-PBMC1.Smart-seq2.p4,MAGIC-Smart-seq2

In [51]:
df_magic.columns =annotation_magic.Cell
df_magic.columns.name = None
df_magic[:3]

,MAGIC-PBMC1.Smart-seq2.p4_A12,MAGIC-PBMC1.Smart-seq2.p4_A2,MAGIC-PBMC1.Smart-seq2.p4_A3,MAGIC-PBMC1.Smart-seq2.p4_A4,MAGIC-PBMC1.Smart-seq2.p4_A7,MAGIC-PBMC1.Smart-seq2.p4_A8,MAGIC-PBMC1.Smart-seq2.p4_A9,MAGIC-PBMC1.Smart-seq2.p4_B1,MAGIC-PBMC1.Smart-seq2.p2_B5,MAGIC-PBMC1.Smart-seq2.p4_B10,...,MAGIC-PBMC2.inDrops.TGAATAGG-TTATGCGA-CACTTTCT,MAGIC-PBMC2.inDrops.TGAATCCT-TTATGCGA-AAACCTCC,MAGIC-PBMC2.inDrops.TGAGAGCG-TTATGCGA-CAGACCAT,MAGIC-PBMC2.inDrops.TGAGAGCG-TTATGCGA-TCTAGCAG,MAGIC-PBMC2.inDrops.TGAGAGCG-TTATGCGA-TCTGTGGT,MAGIC-PBMC2.inDrops.TGAGCACA-GAGCCTTA-TTCCGAGT,MAGIC-PBMC2.inDrops.TGCGACTA-TTATGCGA-TGTTCCAG,MAGIC-PBMC2.inDrops.TGCTTCAT-TTATGCGA-GTTTACGT,MAGIC-PBMC2.inDrops.TGGACGGA-GAGCCTTA-TGGCTACC,MAGIC-PBMC2.inDrops.TGGGAATT-TTATGCGA-AGGTTGTG
TSPAN6,0.109723,0.181646,0.075158,0.116502,0.161529,0.110286,0.105154,0.082984,0.131318,0.120644,...,0.013889,0.003145,0.004863,0.009698,0.001725,0.015106,0.005213,0.016173,0.005972,0.002791
TNMD,0.000000,0.015524,0.000039,0.000000,0.018532,0.041362,0.016647,0.001406,0.016901,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
DPM1,1.760610,0.913213,1.299496,1.736762,1.035799,1.092281,1.173300,1.291313,1.056744,1.831068,...,0.341420,0.422672,0.410878,0.322135,0.402214,0.155478,0.781888,0.461726,0.360707,0.312815

In [ ]:
annotation_magic.to_csv("./d5_MAGIC_cutoff03_583cells/annotation583cell_MAGIC.tsv", sep='\t', index=None)

In [ ]:
df_magic.to_pickle("./d5_MAGIC_cutoff03_583cells/adata_PBMC_MAGIC_583cells.p")

In [37]:
print(df_magic.values.max())
print(np.median(df_magic.values)) 
print(df_magic.values.min())

16.084100261812683
0.027479642146248574
0.0

In [54]:
df_magic_cutoff_03 = df_magic.copy()
df_magic_cutoff_03[:] = np.where(df_magic_cutoff_03 >= 0.027, 1, 0)
df_magic_cutoff_03.stack().value_counts()

1.0    61394651
0.0    61059831
Name: count, dtype: int64

In [57]:
t=0.001
df_magic_cutoff_t = df_magic.copy()
df_magic_cutoff_t[:] = np.where(df_magic_cutoff_t >= t, 1, 0)
df_magic_cutoff_t.stack().value_counts()

1.0    78278471
0.0    44176011
Name: count, dtype: int64